apiVersion: v1
kind: Namespace
metadata:
  name: otel-ns
  # labels:
  #   openshift.io/user-monitoring: "false"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector-sa
  namespace: otel-ns
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: otel-collector-role
rules:
  - apiGroups: ['']
    resources: ['pods', 'namespaces', 'nodes']
    verbs: ['get', 'watch', 'list']
  - apiGroups: ['apps']
    resources: ['replicasets', 'deployments', 'daemonsets', 'statefulsets']
    verbs: ['get', 'watch', 'list']
  - apiGroups: ['batch']
    resources: ['jobs', 'cronjobs']
    verbs: ['get', 'list', 'watch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector-role-sa-binding
subjects:
  - kind: ServiceAccount
    name: otel-collector-sa
    namespace: otel-ns
roleRef:
  kind: ClusterRole
  name: otel-collector-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: otel-ns
spec:
  networkPolicy:
    enabled: true
  observability:
    metrics:
      enableMetrics: true
  deploymentUpdateStrategy: {}
  httpRoute:
    enabled: false
    gateway: ''
  config:
    exporters:
      debug:
        verbosity: normal #basic
      prometheus:
        endpoint: '0.0.0.0:8889'
        without_scope_info: true
        resource_to_telemetry_conversion:
          enabled: true
    processors:
      batch:
        send_batch_max_size: 0
        send_batch_size: 8192
        timeout: 10s
      filter/metrics:
        error_mode: ignore
        metrics:
          metric:
            # - instrumentation_scope.name == "io.opentelemetry.runtime-telemetry-java17"
            - instrumentation_scope.name == "io.opentelemetry.runtime-telemetry-java8"
            # - instrumentation_scope.name == "io.opentelemetry.grpc-1.6"
            - instrumentation_scope.name == "io.opentelemetry.exporters.otlp-http"
            - instrumentation_scope.name == "io.opentelemetry.sdk.logs"
            - instrumentation_scope.name == "io.opentelemetry.sdk.trace"
            # - 'not IsMatch(name, "^sdi[_.]")'
      filter/traces:
        error_mode: ignore
        traces:
          span:
            - 'attributes["http.route"] == "/health"'
      k8sattributes:
        extract:
          # annotations:
          #   - from: pod
          #     key: esempio.it/servizio_ict
          #     tag_name: esempio.servizio_ict
          metadata:
            - k8s.node.name
            - k8s.namespace.name
            - k8s.deployment.name
            - k8s.pod.name
        # filter:
        #   labels:
        #     - key: esempio.it/servizio-ict
        #       op: equals
        #       value: esempio-0454
        pod_association:
          - sources:
              - from: resource_attribute
                name: k8s.pod.name
              - from: resource_attribute
                name: k8s.namespace.name
          - sources:
              - from: connection
        watch_sync_period: 30s
      # memory_limiter:
      #   check_interval: 1s
      #   limit_mib: 3276
      #   spike_limit_mib: 655
      transform:
        error_mode: ignore
        metric_statements:
          - context: resource
            statements:
              - 'set(attributes["k8s.workload.kind"], "replicaset") where IsString(attributes["k8s.replicaset.name"])'
              - 'set(attributes["k8s.workload.name"], attributes["k8s.replicaset.name"]) where IsString(attributes["k8s.replicaset.name"])'
              - 'set(attributes["k8s.workload.kind"], "deployment") where IsString(attributes["k8s.deployment.name"])'
              - 'set(attributes["k8s.workload.name"], attributes["k8s.deployment.name"]) where IsString(attributes["k8s.deployment.name"])'
              - 'delete_key(attributes, "k8s.deployment.name")'
      transform/clean_resource:
        error_mode: ignore
        metric_statements:
          - context: resource
            statements:
              # Mantiene SOLO gli attributi necessari per identificare servizio e infrastruttura K8s
              - keep_keys(attributes, ["service.name", "k8s.namespace.name", "k8s.pod.name", "k8s.node.name", "k8s.workload.kind", "k8s.workload.name"])
    receivers:
      otlp:
        protocols:
          http:
            endpoint: '0.0.0.0:4318'
    service:
      pipelines:
        metrics/pull:
          exporters:
            - debug
            - prometheus
          processors:
            # - memory_limiter
            - filter/metrics
            - k8sattributes
            - transform
            - transform/clean_resource
            - batch
          receivers:
            - otlp
      telemetry:
        metrics:
          level: basic
          readers:
            - pull:
                exporter:
                  prometheus:
                    host: 0.0.0.0
                    port: 8888
                    without_scope_info: false
                    without_type_suffix: false
                    without_units: false
  mode: deployment
  # resources:
  #   limits:
  #     cpu: 1000m
  #     memory: 4Gi
  #   requests:
  #     cpu: 750m
  #     memory: 2Gi
  podDnsConfig: {}
  # env:
  #   - name: GOMEMLIMIT
  #     value: 3276MiB
  managementState: managed
  upgradeStrategy: automatic
  ingress:
    route: {}
  # autoscaler:
  #   behavior:
  #     scaleDown:
  #       policies:
  #         - periodSeconds: 60
  #           type: Pods
  #           value: 2
  #       selectPolicy: Min
  #       stabilizationWindowSeconds: 300
  #     scaleUp:
  #       policies:
  #         - periodSeconds: 60
  #           type: Percent
  #           value: 100
  #       selectPolicy: Max
  #       stabilizationWindowSeconds: 60
  #   maxReplicas: 20
  #   minReplicas: 1
  #   targetCPUUtilization: 75
  serviceAccount: otel-collector-sa
  daemonSetUpdateStrategy: {}
  targetAllocator:
    allocationStrategy: consistent-hashing
    collectorNotReadyGracePeriod: 30s
    collectorTargetReloadInterval: 30s
    filterStrategy: relabel-config
    observability:
      metrics: {}
    prometheusCR:
      evaluationInterval: 30s
      podMonitorNamespaceSelector: {}
      probeNamespaceSelector: {}
      scrapeConfigNamespaceSelector: {}
      scrapeInterval: 30s
      serviceMonitorNamespaceSelector: {}
    resources: {}
  replicas: 1
  ipFamilyPolicy: SingleStack
  configVersions: 3
---
# Opzionale - Creato da operatore
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: otel-collector-monitoring
#   namespace: otel-ns
# spec:
#   endpoints:
#   - interval: 30s
#     port: monitoring
#     scheme: http
#   selector:
#     matchLabels:
#       operator.opentelemetry.io/collector-service-type: monitoring
#   serviceDiscoveryRole: EndpointSlice